import type {
  Account,
  AnalyticsData,
  BalanceInfo,
  Bill,
  BudgetCategory,
  DashboardData,
  MoneyPocket,
  Transaction,
  Workspace,
} from '../lib/types'

export const WORKSPACES: Workspace[] = [
  {
    id: 'srilanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    currency: { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
    theme: 'green',
    warningThreshold: 20000,
    warningMessage:
      'Your available balance is below the recommended minimum balance. Consider reducing unnecessary expenses or adding funds to stay financially comfortable.',
    shortCode: 'LK',
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    country: 'Indonesia',
    currency: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
    theme: 'blue',
    warningThreshold: 5000000,
    warningMessage:
      'Your available balance is below the recommended minimum balance. Consider reducing unnecessary expenses or adding funds to stay financially comfortable.',
    shortCode: 'ID',
  },
]

export const BALANCE_INFO: Record<string, BalanceInfo> = {
  'srilanka': {
    totalBalance: 387500,
    income: 125000,
    expenses: 86250,
    remaining: 38750,
    safeSpending: 125000,
    availableBalance: 18500,
  },
  'indonesia': {
    totalBalance: 18500000,
    income: 8500000,
    expenses: 4200000,
    remaining: 4300000,
    safeSpending: 8500000,
    availableBalance: 18500000,
  },
}

export const UPCOMING_BILLS: Record<string, Bill[]> = {
  'srilanka': [
    {
      id: 'bill-1',
      title: 'Netflix',
      amount: 1500,
      dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '🎬',
      provider: 'Netflix',
    },
    {
      id: 'bill-2',
      title: 'Electricity',
      amount: 4500,
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '💡',
      provider: 'CEB',
    },
    {
      id: 'bill-3',
      title: 'Internet',
      amount: 3200,
      dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '📶',
      provider: 'Dialog',
    },
    {
      id: 'bill-4',
      title: 'Water Bill',
      amount: 1800,
      dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '🚰',
      provider: 'NWSDB',
    },
  ],
  'indonesia': [
    {
      id: 'bill-1',
      title: 'Netflix',
      amount: 159000,
      dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '🎬',
      provider: 'Netflix',
    },
    {
      id: 'bill-2',
      title: 'Electricity',
      amount: 450000,
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '💡',
      provider: 'PLN',
    },
    {
      id: 'bill-3',
      title: 'Internet',
      amount: 320000,
      dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '📶',
      provider: 'Telkom',
    },
    {
      id: 'bill-4',
      title: 'Water Bill',
      amount: 180000,
      dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      icon: '🚰',
      provider: 'PDAM',
    },
  ],
}

export const MONEY_POCKETS: Record<string, MoneyPocket[]> = {
  'srilanka': [
    {
      id: 'pocket-1',
      name: 'Home',
      icon: '🏠',
      currentAmount: 125000,
      targetAmount: 500000,
      status: 'on-track',
    },
    {
      id: 'pocket-2',
      name: 'Emergency Fund',
      icon: '🐷',
      currentAmount: 85000,
      targetAmount: 300000,
      status: 'behind',
    },
    {
      id: 'pocket-3',
      name: 'Education',
      icon: '🎓',
      currentAmount: 45000,
      targetAmount: 200000,
      status: 'on-track',
    },
    {
      id: 'pocket-4',
      name: 'Vacation',
      icon: '✈️',
      currentAmount: 28000,
      targetAmount: 150000,
      status: 'just-started',
    },
  ],
  'indonesia': [
    {
      id: 'pocket-1',
      name: 'Home',
      icon: '🏠',
      currentAmount: 5500000,
      targetAmount: 25000000,
      status: 'on-track',
    },
    {
      id: 'pocket-2',
      name: 'Emergency Fund',
      icon: '🐷',
      currentAmount: 3200000,
      targetAmount: 15000000,
      status: 'behind',
    },
    {
      id: 'pocket-3',
      name: 'Education',
      icon: '🎓',
      currentAmount: 1800000,
      targetAmount: 10000000,
      status: 'on-track',
    },
    {
      id: 'pocket-4',
      name: 'Vacation',
      icon: '✈️',
      currentAmount: 1200000,
      targetAmount: 8000000,
      status: 'just-started',
    },
  ],
}

export const TRANSACTIONS: Record<string, Transaction[]> = {
  'srilanka': [
    {
      id: 'tx-1',
      description: 'Netflix Subscription',
      category: 'Subscription',
      date: '2026-07-29',
      amount: -1500,
      icon: '🎬',
    },
    {
      id: 'tx-2',
      description: 'Salary Deposit',
      category: 'Salary',
      date: '2026-07-28',
      amount: 125000,
      icon: '💰',
    },
    {
      id: 'tx-3',
      description: 'Grocery Shopping',
      category: 'Groceries',
      date: '2026-07-27',
      amount: -8500,
      icon: '🛒',
    },
    {
      id: 'tx-4',
      description: 'Coffee Shop',
      category: 'Food & Dining',
      date: '2026-07-27',
      amount: -850,
      icon: '☕',
    },
    {
      id: 'tx-5',
      description: 'Electricity Bill',
      category: 'Bills & Utilities',
      date: '2026-07-26',
      amount: -4500,
      icon: '💡',
    },
    {
      id: 'tx-6',
      description: 'Freelance Payment',
      category: 'Investment',
      date: '2026-07-25',
      amount: 25000,
      icon: '📈',
    },
    {
      id: 'tx-7',
      description: 'Transportation',
      category: 'Transportation',
      date: '2026-07-25',
      amount: -2200,
      icon: '🚗',
    },
    {
      id: 'tx-8',
      description: 'Book Purchase',
      category: 'Education',
      date: '2026-07-24',
      amount: -3200,
      icon: '📚',
    },
  ],
  'indonesia': [
    {
      id: 'tx-1',
      description: 'Netflix Subscription',
      category: 'Subscription',
      date: '2026-07-29',
      amount: -159000,
      icon: '🎬',
    },
    {
      id: 'tx-2',
      description: 'Salary Deposit',
      category: 'Salary',
      date: '2026-07-28',
      amount: 8500000,
      icon: '💰',
    },
    {
      id: 'tx-3',
      description: 'Grocery Shopping',
      category: 'Groceries',
      date: '2026-07-27',
      amount: -350000,
      icon: '🛒',
    },
    {
      id: 'tx-4',
      description: 'Coffee Shop',
      category: 'Food & Dining',
      date: '2026-07-27',
      amount: -45000,
      icon: '☕',
    },
    {
      id: 'tx-5',
      description: 'Electricity Bill',
      category: 'Bills & Utilities',
      date: '2026-07-26',
      amount: -450000,
      icon: '💡',
    },
    {
      id: 'tx-6',
      description: 'Freelance Payment',
      category: 'Investment',
      date: '2026-07-25',
      amount: 1250000,
      icon: '📈',
    },
    {
      id: 'tx-7',
      description: 'Transportation',
      category: 'Transportation',
      date: '2026-07-25',
      amount: -85000,
      icon: '🚗',
    },
    {
      id: 'tx-8',
      description: 'Book Purchase',
      category: 'Education',
      date: '2026-07-24',
      amount: -120000,
      icon: '📚',
    },
  ],
}

export const ANALYTICS_DATA: Record<string, AnalyticsData> = {
  'srilanka': {
    availableBalance: 18500,
    totalIncome: 150000,
    totalExpense: 20850,
    remainingBudget: 129150,
    monthlyCashflow: 129150,
    healthScore: 78,
    savingsRate: 31,
    categorySpending: [
      { category: 'Bills & Utilities', amount: 5950, percentage: 29, icon: '💡' },
      { category: 'Food & Dining', amount: 850, percentage: 4, icon: '☕' },
      { category: 'Groceries', amount: 8500, percentage: 41, icon: '🛒' },
      { category: 'Transportation', amount: 2200, percentage: 11, icon: '🚗' },
      { category: 'Education', amount: 3200, percentage: 15, icon: '📚' },
      { category: 'Subscription', amount: 1500, percentage: 7, icon: '🎬' },
    ],
    budgetProgress: [95, 65, 45, 20],
  },
  'indonesia': {
    availableBalance: 18500000,
    totalIncome: 9750000,
    totalExpense: 1029000,
    remainingBudget: 8721000,
    monthlyCashflow: 8721000,
    healthScore: 85,
    savingsRate: 51,
    categorySpending: [
      { category: 'Bills & Utilities', amount: 450000, percentage: 44, icon: '💡' },
      { category: 'Food & Dining', amount: 45000, percentage: 4, icon: '☕' },
      { category: 'Groceries', amount: 350000, percentage: 34, icon: '🛒' },
      { category: 'Transportation', amount: 85000, percentage: 8, icon: '🚗' },
      { category: 'Education', amount: 120000, percentage: 12, icon: '📚' },
      { category: 'Subscription', amount: 159000, percentage: 2, icon: '🎬' },
    ],
    budgetProgress: [22, 11, 18, 15],
  },
}

export const MONTHLY_ANALYTICS_DATA: Record<
  string,
  { month: string; income: number; expenses: number; savings: number }[]
> = {
  'srilanka': [
    { month: 'Jan', income: 110000, expenses: 85000, savings: 25000 },
    { month: 'Feb', income: 115000, expenses: 82000, savings: 33000 },
    { month: 'Mar', income: 120000, expenses: 88000, savings: 32000 },
    { month: 'Apr', income: 125000, expenses: 86000, savings: 39000 },
    { month: 'May', income: 125000, expenses: 90000, savings: 35000 },
    { month: 'Jun', income: 125000, expenses: 86250, savings: 38750 },
  ],
  'indonesia': [
    { month: 'Jan', income: 8000000, expenses: 4500000, savings: 3500000 },
    { month: 'Feb', income: 8200000, expenses: 4300000, savings: 3900000 },
    { month: 'Mar', income: 8500000, expenses: 4400000, savings: 4100000 },
    { month: 'Apr', income: 8500000, expenses: 4200000, savings: 4300000 },
    { month: 'May', income: 8500000, expenses: 4300000, savings: 4200000 },
    { month: 'Jun', income: 8500000, expenses: 4200000, savings: 4300000 },
  ],
}

const ACCOUNTS_MOCK: Record<string, Account[]> = {
  'srilanka': [
    {
      id: 'acc-1',
      name: 'Main Account',
      type: 'Checking',
      icon: '🏦',
      accountNumber: '**** 4567',
      balance: 225000,
      status: 'primary',
      lastUpdated: '2026-07-29',
    },
    {
      id: 'acc-2',
      name: 'Savings Account',
      type: 'Savings',
      icon: '🐷',
      accountNumber: '**** 8901',
      balance: 125000,
      status: 'active',
      lastUpdated: '2026-07-28',
    },
    {
      id: 'acc-3',
      name: 'Cash Wallet',
      type: 'Cash',
      icon: '💵',
      accountNumber: 'N/A',
      balance: 37500,
      status: 'active',
      lastUpdated: '2026-07-27',
    },
    {
      id: 'acc-4',
      name: 'E-Wallet',
      type: 'Digital',
      icon: '📱',
      accountNumber: '**** 2345',
      balance: 2500,
      status: 'active',
      lastUpdated: '2026-07-29',
    },
  ],
  'indonesia': [
    {
      id: 'acc-1',
      name: 'Main Account',
      type: 'Checking',
      icon: '🏦',
      accountNumber: '**** 4567',
      balance: 8500000,
      status: 'primary',
      lastUpdated: '2026-07-29',
    },
    {
      id: 'acc-2',
      name: 'Savings Account',
      type: 'Savings',
      icon: '🐷',
      accountNumber: '**** 8901',
      balance: 15000000,
      status: 'active',
      lastUpdated: '2026-07-28',
    },
    {
      id: 'acc-3',
      name: 'Cash Wallet',
      type: 'Cash',
      icon: '💵',
      accountNumber: 'N/A',
      balance: 2500000,
      status: 'active',
      lastUpdated: '2026-07-27',
    },
    {
      id: 'acc-4',
      name: 'E-Wallet',
      type: 'Digital',
      icon: '📱',
      accountNumber: '**** 2345',
      balance: 500000,
      status: 'active',
      lastUpdated: '2026-07-29',
    },
  ],
}

export { ACCOUNTS_MOCK }

export const BUDGET_CATEGORIES: Record<string, BudgetCategory[]> = {
  'srilanka': [
    { id: 'food', name: 'Food', icon: '🍽️', allocated: 45000, spent: 38500 },
    { id: 'transport', name: 'Transportation', icon: '🚗', allocated: 25000, spent: 22000 },
    { id: 'shopping', name: 'Shopping', icon: '🛍️', allocated: 35000, spent: 18500 },
    { id: 'bills', name: 'Bills', icon: '💡', allocated: 50000, spent: 45000 },
    { id: 'entertainment', name: 'Entertainment', icon: '🎮', allocated: 20000, spent: 22500 },
    { id: 'healthcare', name: 'Healthcare', icon: '🏥', allocated: 15000, spent: 8500 },
  ],
  'indonesia': [
    { id: 'food', name: 'Food', icon: '🍽️', allocated: 2500000, spent: 2100000 },
    { id: 'transport', name: 'Transportation', icon: '🚗', allocated: 1500000, spent: 85000 },
    { id: 'shopping', name: 'Shopping', icon: '🛍️', allocated: 2000000, spent: 950000 },
    { id: 'bills', name: 'Bills', icon: '💡', allocated: 3500000, spent: 3200000 },
    { id: 'entertainment', name: 'Entertainment', icon: '🎮', allocated: 1200000, spent: 850000 },
    { id: 'healthcare', name: 'Healthcare', icon: '🏥', allocated: 1000000, spent: 450000 },
  ],
}

export const DASHBOARD_DATA: DashboardData = {
  balance: BALANCE_INFO,
  upcomingBills: UPCOMING_BILLS,
  moneyPockets: MONEY_POCKETS,
  transactions: TRANSACTIONS,
  workspaces: WORKSPACES,
  accounts: ACCOUNTS_MOCK,
  analytics: ANALYTICS_DATA,
  budgets: BUDGET_CATEGORIES,
}
